services:
  postgres:
    image: postgres:17
    container_name: tinnova-postgres
    environment:
      POSTGRES_DB: veiculosdb
      POSTGRES_USER: tinnova
      POSTGRES_PASSWORD: tinnova
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

