spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/veiculosdb
    username: tinnova
    password: tinnova
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
server:
  port: 8080
